import com.itextpdf.text.Chunk;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.io.File;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;
import project.*;
import com.itextpdf.text.*;
 
import com.itextpdf.text.pdf.*;  


import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;

/*

 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aditya
 */
public class CustomerCheckOut extends javax.swing.JFrame {

    /**
     * Creates new form CustomerCheckOut
     */
    public CustomerCheckOut() {
        initComponents();
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jTextField7.setEditable(false);
        jTextField8.setEditable(false);
        jTextField9.setEditable(false);
    }
    int id =0;
    String Query;
    String roomType;
    String bed;
    String roomNo;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 118));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Customer Check Out.png"))); // NOI18N
        jLabel1.setText("Customer Check Out");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 28, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Room Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 200, -1));

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Mobile Number", "Nationality", "Gender", "Email", "ID Proof", "Address", "CheckIn Date", "Price Per Day", "Bed", "Room Types", "Room Number"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(8).setResizable(false);
            jTable1.getColumnModel().getColumn(12).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 1270, 230));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 186, -1, -1));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 224, 251, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Check IN Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 186, -1, -1));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 224, 251, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Check Out Date(Today)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 186, -1, -1));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 224, 250, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Customer Mobile Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 180, -1, -1));

        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 220, 250, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Price Per Day ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 276, 110, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Number Of Days Stay");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 276, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Total Amount To Collect From Customer");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 284, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Email");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 280, -1, -1));

        jTextField6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 322, 251, -1));

        jTextField7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 322, 251, -1));

        jTextField8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 322, 257, -1));

        jTextField9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 320, 250, -1));

        jButton3.setBackground(new java.awt.Color(102, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Check Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 366, -1, -1));

        jButton4.setBackground(new java.awt.Color(102, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 366, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all pages background.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
        ResultSet rs = Select.getData("select * from customer where checkOut is NULL");
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        try {
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(1) ,rs.getString(2) ,rs.getString(3) ,rs.getString(4) ,rs.getString(5) ,rs.getString(6) ,rs.getString(8) ,rs.getString(7) ,rs.getString(9) ,rs.getString(13) ,rs.getString(11) ,rs.getString(12) ,rs.getString(10) ,});
            }
            rs.close();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String roomNo = jTextField1.getText();
    try {
        ResultSet rs = Select.getData("select * from customer where roomNumber='" + roomNo + "' and checkOut is NULL");
        if (rs.next()) {
            jTextField1.setEditable(false);
            id = rs.getInt(1);
            jTextField2.setText(rs.getString(2));
            jTextField3.setText(rs.getString(9));
            jTextField5.setText(rs.getString(3));
            jTextField6.setText(rs.getString(13));

            SimpleDateFormat myFormat = new SimpleDateFormat("dd/MM/yyyy");
            Calendar cal = Calendar.getInstance();
            jTextField4.setText(myFormat.format(cal.getTime()));
            String dateBeforeString = rs.getString(9);
            java.util.Date dateBefore = myFormat.parse(dateBeforeString);
            String dateAfterString = myFormat.format(cal.getTime());
            java.util.Date dateAfter = myFormat.parse(dateAfterString);
            long difference = dateAfter.getTime() - dateBefore.getTime();
            int noOfDayStay = (int) (difference / (1000 * 60 * 60 * 24));

            // Ensure at least 1 day is charged
            if (noOfDayStay == 0) {
                noOfDayStay = 1;
            }
            jTextField7.setText(String.valueOf(noOfDayStay));
            float price = Float.parseFloat(jTextField6.getText());
            jTextField8.setText(String.valueOf(noOfDayStay * price));
            jTextField9.setText(rs.getString(6));
            roomType = rs.getString(12);
            bed = rs.getString(11);
        } else {
            JOptionPane.showMessageDialog(null, "Room Number is Not Booked or Room Number does not Exist");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CustomerCheckOut().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String name = jTextField2.getText();
        String mobileNumber = jTextField5.getText();
        String email = jTextField9.getText();
        
        String checkOut = jTextField4.getText();
        String numberOfDaysStay = jTextField7.getText();
        String totalAmount = jTextField8.getText();
        roomNo = jTextField1.getText();
        Query = "update customer set numberOfDaysStay = '"+numberOfDaysStay+"' ,totalAmount = '"+totalAmount+"' ,checkOut='"+checkOut+"' where id ='" +id+"'";
        InsertUpdateDelete.setData(Query, "");
        Query="update room set Status='Not Booked' where roomNo = '"+roomNo+"'";
        InsertUpdateDelete.setData(Query, "");
        
        
        String path = "E:\\";  // Set the path for saving the PDF file
com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
try {
//    PdfWriter.getInstance(doc, new FileOutputStream(path + "" + id + ".pdf"));
//    doc.open();
//    
//
//    
//
//  // Make sure this import is included
//
//// Title
//Paragraph paragraph1 = new Paragraph("Namaste Hotel Management System", 
//        FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16, Font.BOLD));
//paragraph1.setAlignment(Element.ALIGN_CENTER);
//doc.add(paragraph1);
//
//// Decorative divider line
//Paragraph paragraph2 = new Paragraph("======================================================================");
//paragraph2.setAlignment(Element.ALIGN_CENTER);
//doc.add(paragraph2);
//
//// Customer Details
//Paragraph paragraph3 = new Paragraph("\nBill ID: " + id, FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12));
//paragraph3.add("\n\nCustomer Details:");
//paragraph3.add("\nName: " + name);
//paragraph3.add("\nMobile Number: " + mobileNumber);
//paragraph3.add("\nEmail: " + email);
//paragraph3.setSpacingBefore(10f);
//doc.add(paragraph3);
//doc.add(paragraph2);
//
//// Room Details
//Paragraph paragraph4 = new Paragraph("\nRoom Details:", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12));
//paragraph4.add("\nNumber: " + roomNo);
//paragraph4.add("\nType: " + roomType);
//paragraph4.add("\nBed: " + bed);
//paragraph4.add("\nPrice per Day: " + jTextField6.getText());
//paragraph4.setSpacingBefore(10f);
//doc.add(paragraph4);
//doc.add(paragraph2);
//
//
//
//
//
//
//
//    // Add table with stay details
//    PdfPTable tb1 = new PdfPTable(4);
//    tb1.addCell("Check IN Date: " + jTextField3.getText());
//    tb1.addCell("Check OUT Date: " + checkOut);
//    tb1.addCell("No of Days Stay: " + numberOfDaysStay);
//    tb1.addCell("Total Amount paid: " + totalAmount);
//    doc.add(tb1);
//    doc.add(paragraph2);
//
//    
//
//
//
//
//// Add Address with Hyperlink
//Paragraph addressParagraph = new Paragraph("📍 Address: ", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12));
//Chunk addressLink = new Chunk("Click here for Google Maps", FontFactory.getFont(FontFactory.HELVETICA, 12, BaseColor.BLUE));
//addressLink.setUnderline(0.1f, -2f); // Underline effect
//addressLink.setAnchor("https://maps.app.goo.gl/khhQUEkNGJ4bnF98A"); // Direct link
//addressParagraph.add(addressLink);
//doc.add(addressParagraph);
//
//// Add Phone Number with Icon
//Paragraph phoneParagraph = new Paragraph("📞 Connect with Hotel Manager: ", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12));
//phoneParagraph.add(new Chunk("8603731247 (Dilip kumar)", FontFactory.getFont(FontFactory.HELVETICA, 12, Font.BOLD, BaseColor.BLACK)));
//doc.add(phoneParagraph);
//doc.add(paragraph2); // Divider line
//
//// Add closing message with styling
//Paragraph paragraph5 = new Paragraph("\n 🙏 Thank You for Choosing Us! We Look Forward to Your Next Visit. 🙏", 
//        FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, Font.BOLD, BaseColor.DARK_GRAY));
//paragraph5.setAlignment(Element.ALIGN_CENTER);
//doc.add(paragraph5);
//
//
//} catch (DocumentException | FileNotFoundException e) {
//    JOptionPane.showMessageDialog(null, e);
//}
//doc.close();

PdfWriter.getInstance(doc, new FileOutputStream(path + "" + id + ".pdf"));
doc.open();

// Title
Paragraph title = new Paragraph("Namaste Hotel Management System", 
    FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, Font.BOLD, BaseColor.DARK_GRAY));
title.setAlignment(Element.ALIGN_CENTER);
title.setSpacingAfter(10f);  // Adding space below title
doc.add(title);

// Decorative Divider Line
Paragraph divider = new Paragraph("======================================================================");
divider.setAlignment(Element.ALIGN_CENTER);
divider.setSpacingAfter(15f);  // Space below the line
doc.add(divider);

// Customer Details Section
Paragraph customerDetails = new Paragraph("Customer Details:", 
    FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, Font.BOLD, BaseColor.BLACK));
customerDetails.setSpacingBefore(10f);
doc.add(customerDetails);

Paragraph customerInfo = new Paragraph();
customerInfo.add("Bill ID: " + id + "\n");
customerInfo.add("Name: " + name + "\n");
customerInfo.add("Mobile Number: " + mobileNumber + "\n");
customerInfo.add("Email: " + email + "\n");
customerInfo.setFont(FontFactory.getFont(FontFactory.HELVETICA, 12));
customerInfo.setSpacingAfter(15f);  // Space below customer info
doc.add(customerInfo);

// Room Details Section
Paragraph roomDetails = new Paragraph("Room Details:", 
    FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, Font.BOLD, BaseColor.BLACK));
roomDetails.setSpacingBefore(10f);
doc.add(roomDetails);

Paragraph roomInfo = new Paragraph();
roomInfo.add("Room Number: " + roomNo + "\n");
roomInfo.add("Room Type: " + roomType + "\n");
roomInfo.add("Bed Type: " + bed + "\n");
roomInfo.add("Price per Day: ₹" + jTextField6.getText() + "\n");
roomInfo.setFont(FontFactory.getFont(FontFactory.HELVETICA, 12));
roomInfo.setSpacingAfter(15f);  // Space below room info
doc.add(roomInfo);

// Stay Details Table
PdfPTable stayDetailsTable = new PdfPTable(4);
stayDetailsTable.setWidthPercentage(100);
stayDetailsTable.addCell(new Phrase("Check-In Date: " + jTextField3.getText(), FontFactory.getFont(FontFactory.HELVETICA, 12)));
stayDetailsTable.addCell(new Phrase("Check-Out Date: " + checkOut, FontFactory.getFont(FontFactory.HELVETICA, 12)));
stayDetailsTable.addCell(new Phrase("No of Days: " + numberOfDaysStay, FontFactory.getFont(FontFactory.HELVETICA, 12)));
stayDetailsTable.addCell(new Phrase("Total Amount: ₹" + totalAmount, FontFactory.getFont(FontFactory.HELVETICA, 12)));
doc.add(stayDetailsTable);
doc.add(divider);  // Adding the divider line again

// Payment Breakdown Section (new content)
Paragraph paymentDetails = new Paragraph("Payment Breakdown:", 
    FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, Font.BOLD, BaseColor.BLACK));
paymentDetails.setSpacingBefore(10f);
doc.add(paymentDetails);

PdfPTable paymentTable = new PdfPTable(2);
paymentTable.setWidthPercentage(100);
paymentTable.addCell("Room Charges");
paymentTable.addCell("₹" + jTextField6.getText());
paymentTable.addCell("Taxes");
paymentTable.addCell("₹" + calculateTaxes(totalAmount));  // Assuming you have a method to calculate taxes
paymentTable.addCell("Discount (if any)");
paymentTable.addCell("₹" + calculateDiscount(totalAmount));  // Assuming a discount function
paymentTable.addCell("Total Amount");
paymentTable.addCell("₹" + totalAmount);
doc.add(paymentTable);
doc.add(divider);  // Adding the divider line again

// Terms and Conditions (new content)
Paragraph terms = new Paragraph("Terms and Conditions:", 
    FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, Font.BOLD, BaseColor.BLACK));
terms.setSpacingBefore(10f);
doc.add(terms);

Paragraph termsContent = new Paragraph();
termsContent.add("• Check-in time: 12:00 PM\n");
termsContent.add("• Check-out time: 11:00 AM\n");
termsContent.add("• All payments are due at the time of check-in\n");
termsContent.add("• Cancellations must be made 24 hours in advance to avoid a penalty\n");
termsContent.add("• Please adhere to the hotel's rules and regulations.\n");
termsContent.setFont(FontFactory.getFont(FontFactory.HELVETICA, 12));
termsContent.setSpacingAfter(15f);  // Space below terms
doc.add(termsContent);

// Hotel Facilities (new content)
Paragraph facilities = new Paragraph("Hotel Facilities:", 
    FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, Font.BOLD, BaseColor.BLACK));
facilities.setSpacingBefore(10f);
doc.add(facilities);

Paragraph facilitiesContent = new Paragraph();
facilitiesContent.add("• Free Wi-Fi\n");
facilitiesContent.add("• Swimming Pool\n");
facilitiesContent.add("• Gym\n");
facilitiesContent.add("• 24/7 Room Service\n");
facilitiesContent.add("• In-house Restaurant\n");
facilitiesContent.setFont(FontFactory.getFont(FontFactory.HELVETICA, 12));
facilitiesContent.setSpacingAfter(15f);  // Space below facilities section
doc.add(facilitiesContent);

// Address Section with Hyperlink
Paragraph address = new Paragraph("📍 Address: ", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12));
Chunk addressLink = new Chunk("Click here for Google Maps", FontFactory.getFont(FontFactory.HELVETICA, 12, BaseColor.BLUE));
addressLink.setUnderline(0.1f, -2f);  // Underline effect
addressLink.setAnchor("https://maps.app.goo.gl/khhQUEkNGJ4bnF98A"); // Hyperlink
address.add(addressLink);
address.setSpacingAfter(15f);  // Space below the address section
doc.add(address);

// Phone Number Section with Icon
Paragraph phone = new Paragraph("📞 Contact the Hotel Manager: ", 
    FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12));
phone.add(new Chunk("8603731247 (Dilip Kumar)", FontFactory.getFont(FontFactory.HELVETICA, 12, Font.BOLD, BaseColor.BLACK)));
phone.setSpacingAfter(15f);  // Space below phone section
doc.add(phone);
doc.add(divider);  // Divider after phone section

// Feedback Section (new content)
Paragraph feedback = new Paragraph("We value your feedback!", 
    FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, Font.BOLD, BaseColor.GREEN));
feedback.setSpacingBefore(10f);
doc.add(feedback);

Paragraph feedbackContent = new Paragraph();
feedbackContent.add("Please provide your feedback on our services to help us improve:\n");
feedbackContent.add("• Rate your stay experience (1-5)\n");
feedbackContent.add("• Suggestions for improvement\n");
feedbackContent.setFont(FontFactory.getFont(FontFactory.HELVETICA, 12));
feedbackContent.setSpacingAfter(15f);  // Space below feedback section
doc.add(feedbackContent);

// Closing Message
Paragraph closingMessage = new Paragraph("\n🙏 Thank You for Choosing Us! We Look Forward to Your Next Visit. 🙏", 
    FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, Font.BOLD, BaseColor.DARK_GRAY));
closingMessage.setAlignment(Element.ALIGN_CENTER);
closingMessage.setSpacingBefore(20f);  // Space before the message
doc.add(closingMessage);

} catch (DocumentException | FileNotFoundException e) {
    JOptionPane.showMessageDialog(null, e);
}
doc.close();

        
        

          
        int a = JOptionPane.showConfirmDialog(null, "Do You want to print the Bill?", "Select", JOptionPane.YES_NO_OPTION);
if (a == 0) {
    try {
        File file = new File("E:\\" + id + ".pdf");
        if (file.exists()) {
            Process p = Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler E:\\" + id + ".pdf");
        } else {
            System.out.print("File does not exist");
        }
    } catch (Exception e) {
        JOptionPane.showConfirmDialog(null, e);
    }
}

        setVisible(false);
        new CustomerCheckOut().setVisible(true);   
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CustomerCheckOut().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
